# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: DB_MYSQL_DESAENV08_MEAWDB_MEAWDB_ENDPOINT
    db: meawdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: meawdb_WPROD
    password: DB_MYSQL_DESAENV08_MEAWDB_MEAWDB_WPROD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: none